logo:
  subtitle: 'ä¸€èŠ±ä¸€ä¸–ç•Œï¼Œä¸€å¶ä¸€è©æ | ğŸ“«: hoi3vel@gmail.com'
  style:
    leftbar:
      background-image: url(https://img.hoi3vel.cn/config/background.webp)
      blur-px: 100px # æ¨¡ç³ŠåŠå¾„
      blur-bg: var(--bg-a60) # æ¨¡ç³Šé¢œè‰²

# ä¾§è¾¹æ ä¸»åŠŸèƒ½å¯¼èˆªèœå•
menubar:
  columns: 4 # ä¸€è¡Œå¤šå°‘ä¸ª
  items: # å¯æŒ‰ç…§è‡ªå·±éœ€æ±‚å¢åŠ ï¼Œç¬¦åˆä»¥ä¸‹æ ¼å¼å³å¯
    - id: about
      theme: '#815C94'
      # icon: solar:notebook-bookmark-bold-duotone
      title: å…³äº
      url: /about/
    - id: post # é¡µé¢ä¸­é«˜äº®çš„ menu_id
      theme: '#AE88C3' # é«˜äº®æ—¶çš„é¢œè‰²ï¼Œä»… svg ä¸­ fill="currentColor" æ—¶æœ‰æ•ˆ
      # icon: solar:documents-bold-duotone # æ”¯æŒ svg/img æ ‡ç­¾ï¼Œå¯ä»¥å®šä¹‰åœ¨ icons.yml æ–‡ä»¶ä¸­ï¼Œä¹Ÿæ”¯æŒå¤–éƒ¨å›¾ç‰‡çš„ URL
      title: æ–‡ç«  # æ ‡é¢˜
      url: / # è·³è½¬é“¾æ¥ï¼Œæ”¯æŒç›¸å¯¹è·¯å¾„å’Œç»å¯¹è·¯å¾„
    - id: social
      theme: '#CEA6E3'
      # icon: solar:chat-square-like-bold-duotone
      title: å‹é“¾
      url: /friends/
    - id: tools
      theme: '#EFC6FF'
      # icon: solar:planet-bold-duotone
      title: ä¼ é€é—¨
      url: /explore/

# ä¾§è¾¹æ é¡µè„šä»¥åŠé¡µé¢ç«™ç‚¹
footer:
  social:
    rss:
      icon: '<img src="https://img.hoi3vel.cn/config/rss.svg"/>'
      url: https://www.hoi3vel.cn/atom.xml
    github:
      icon: '<img src="https://img.hoi3vel.cn/config/github.svg"/>'
      url: https://github.com/WYuHwn
    weibo:
      icon: '<img src="https://img.hoi3vel.cn/config/weibo.svg"/>'
      url: https://weibo.com/u/7792806695
    leetcode:
      icon: '<img src="https://img.hoi3vel.cn/config/leetcode.svg"/>'
      url: https://leetcode.cn/u/hoi3vel/
  sitemap:
    - title: å¯¼èˆª
      items:
        - '[è¿‘æœŸå‘å¸ƒ](/)'
        - '[åˆ†ç±»](/categories/)'
        - '[æ ‡ç­¾](/tags/)'
        - '[å½’æ¡£](/archives/)'
    - title: ç¤¾äº¤
      items:
        - '[å‹é“¾](/friends/)'
        - '[å…³äº](/about/)'
    - title: åè®®
      items:
        - '[éšç§æ”¿ç­–](/privacy/)'
        - '[å…è´£å£°æ˜](/claim/)'
    - title: æ›´å¤š
      items:
        - '[ä¼ é€é—¨](/explore/)'
  content:
    æœ¬ç«™ç”± [{author.name}](/) ä½¿ç”¨ [{theme.name} {theme.version}]({theme.tree}) ä¸»é¢˜åˆ›å»ºã€‚</br>
    æœ¬åšå®¢æ‰€æœ‰æ–‡ç« é™¤ç‰¹åˆ«å£°æ˜å¤–ï¼Œå‡é‡‡ç”¨ [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) è®¸å¯åè®®ï¼Œè½¬è½½è¯·æ³¨æ˜å‡ºå¤„ã€‚</br>
    [æ¸ICPå¤‡-2024033351å·-1](https://beian.miit.gov.cn/#/Integrated/recordQuery) | [æµ™å…¬ç½‘å®‰å¤‡33019202002449å·](https://beian.mps.gov.cn/#/query/webSearch)

style:
  prefers_theme: auto # æŒ‡å®šç½‘ç«™ä¸»é¢˜æ¨¡å¼ auto/light/dark
  color:
    theme: '#744DA9' # ä¸»é¢˜è‰²
    accent: 'hsl(14 100% 57%)' # å¼ºè°ƒè‰²
    link: '#bc91d8' # è¶…é“¾æ¥é¢œè‰²
  font-family:
    body: '"LXGWWenKai"'
    code: '"JetBrainsMono"'
    codeblock: '"JetBrainsMono"'
  leftbar:
    background-color: var(--card) # var(--block)
    background-image: url(https://img.hoi3vel.cn/config/background.webp)
    blur-px: 100px
    blur-bg: var(--bg-a60)
    background-opacity: 0.8
  site:
    # background-image: 'url(https://gcore.jsdelivr.net/gh/cdn-x/placeholder@1.0.14/image/site-bg1@small.webp)'
    background-image: 'url(https://img.hoi3vel.cn/config/background.webp)'
    blur-px: 100px # æ¨¡ç³ŠåŠå¾„
    blur-bg: var(--bg-a75) # æ¨¡ç³Šé¢œè‰²
  # åœ†è§’å¤§å°
  border-radius:
    card: 12px # å¡ç‰‡åœ†è§’
    block: 12px # å—åœ†è§’
    bar: 6px # å¯¼èˆªæ åœ†è§’
    image: 6px # å›¾ç‰‡åœ†è§’

# åŸºç¡€ä¾èµ–
# åŸºç¡€ä¾èµ–
dependencies:
  # å›¾ç‰‡æ‡’åŠ è½½
  lazyload:
    js: https://gcore.jsdelivr.net/npm/vanilla-lazyload@19.1/dist/lazyload.min.js
    transition: fade # blur, fade
    fix_ratio: true # true / false

# é¡¶éƒ¨tabæ 
site_tree:
  home:
    leftbar: welcome, recent
  blog:
    nav_tabs: # è¿‘æœŸå‘å¸ƒ åˆ†ç±» æ ‡ç­¾ å½’æ¡£ and ...
      #'æœ‹å‹æ–‡ç« ': /friends/rss/ # è¿™é‡Œå¡«å†™çš„é“¾æ¥è¦ä¸å¯¹åº”é¡µé¢ä¸€è‡´ï¼Œå¦åˆ™å¯èƒ½æ— æ³•æ­£ç¡®é«˜äº®
      'è¿‘æœŸå‘å¸ƒ': /
      'åˆ†ç±»': /categories/
      'æ ‡ç­¾': /tags/
      'ä¸“æ ': /topic/
      'å½’æ¡£': /archives/

article:
  share: [wechat, weibo, email, link]

comments:
  service: giscus
  comment_title: ç•™ä¸‹ä½ çš„è¶³è¿¹å­~ğŸ‘£ğŸ‘£ğŸ‘£
  giscus:
    src: https://giscus.app/client.js
    data-repo: WYuHwn/WYuHwn.github.io # [åœ¨æ­¤è¾“å…¥ä»“åº“]
    data-repo-id: R_kgDOMBMT2A # [åœ¨æ­¤è¾“å…¥ä»“åº“ ID]
    data-category: Q&A # [åœ¨æ­¤è¾“å…¥åˆ†ç±»å]
    data-category-id: DIC_kwDOMBMT2M4Cfvy7
    data-mapping: pathname
    data-strict: 0
    data-reactions-enabled: 1
    data-emit-metadata: 0
    data-input-position: top # top, bottom
    data-theme: preferred_color_scheme
    data-lang: zh-CN
    data-loading: lazy
    crossorigin: anonymous